name: sam2
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10.15
  - pip:
      - boxmot==10.0.52
      - ultralytics==8.3.27
      - matplotlib
      - opencv-python
      - ultralytics
      - wandb
      - timm