NUM_OBJECTS = 1
YOLO_CHECKPOINT_FILEPATH = "yolov8x-seg.pt"
SAM_CHECKPOINT_FILEPATH = "../checkpoints/sam2.1_hiera_base_plus.pt"
SAM_CONFIG_FILEPATH = "./configs/samurai/sam2.1_hiera_b+.yaml"
DEVICE = 'cuda:0'
#VIDEO_PATH = "http://stage-ams-nfs.srv.axds.co/stream/adaptive/ucsc/walton_lighthouse/hls.m3u8"
#VIDEO_PATH = "./videos/twinlakes/8/walton_lighthouse-2024-11-16-164421Z.mp4"
#VIDEO_PATH = "./videos/seabright_new/walton_lighthouse-2024-01-11-180046Z.mp4"
VIDEO_PATH = "./shoreline_jsons/downloaded_webcoos_clips/jennettes_pier/north_easterly_onshore/bin_5/jennette_north-2025-01-24_202403Z.mp4"
DESIRED_FPS = 5
FRAME_INTERVAL = 1.0 / DESIRED_FPS
RESTART_INTERVAL = 40
RETRY_FRAMES = 50
