NUM_OBJECTS = 1
YOLO_CHECKPOINT_FILEPATH = "yolov8x-seg.pt"
SAM_CHECKPOINT_FILEPATH = "../checkpoints/sam2.1_hiera_base_plus.pt"
SAM_CONFIG_FILEPATH = "./configs/samurai/sam2.1_hiera_b+.yaml"
DEVICE = 'cuda:0'
VIDEO_PATH = "http://stage-ams-nfs.srv.axds.co/stream/adaptive/noaa/tmmc_prls/hls.m3u8"
# VIDEO_PATH = "./videos/santacruzwharf-2026-01-04-231018Z.mp4"
DESIRED_FPS = 10
FRAME_INTERVAL = 1.0 / DESIRED_FPS
RESTART_INTERVAL = 500
RETRY_FRAMES = 80
STREAM_SERVER_HOST = "localhost"
STREAM_SERVER_PORT = 8002
STREAM_SERVER_JPEG_QUALITY = 80
STREAM_SERVER_FPS = 15
